bring up the `CreateFlashcard` modal if c is pressed.
NeonLaw/codebase pull request #844
Opened 2020-09-20 15:04 UTC by nisarhassan12

Fixes #843

2020-09-20 15:09 UTC, nisarhassan12 commented
@shicholas I have added the functionality. I was also writing a cypress spec for this and for that I need to use `cy.loginAsAdminUser()` but it won't work unless I provide the credentials. How do I make cypress login as an Admin? Thanks

![image](https://user-images.githubusercontent.com/46004116/93714580-20eb5980-fb7d-11ea-923a-4465a15ca95f.png)

2020-09-20 16:51 UTC, shicholas commented
this is looking good, I hope the docs in #845 help.

2020-09-21 17:27 UTC, shicholas requested changes

2020-09-21 17:27 UTC, shicholas commented on packages/interface/cypress/integration/keyboard-shortcuts.spec.ts
> +      cy.get('.chakra-modal__header').contains('Create a Flashcard');
small change, instead of testing for this class `.chakra-modal__header` I think we should add a `data-testid` attribute to the header and test that this DOM selector exists. Like this https://github.com/NeonLaw/codebase/blob/a8b4bc88f303dd8354e7212a5ee3c87b9920fc8b/packages/interface/cypress/integration/crudFlashcards.spec.ts#L14

I think the reason to test this way is that we don't have control over how `Chakra-UI` names their classes, but we do have control over our use of `data-testid`

2020-09-21 17:32 UTC, shicholas commented on packages/interface/cypress/integration/keyboard-shortcuts.spec.ts
> +      cy.get('.chakra-modal__header').contains('Create a Flashcard');
```suggestion
      cy.get('[data-testid="create-flashcard-modal"]').
        .should('exist');
```

2020-09-21 17:32 UTC, shicholas commented on packages/interface/cypress/integration/keyboard-shortcuts.spec.ts
> +      cy.get('.chakra-modal__header').contains('Create a Flashcard');
@nisarhassan12, you can try the `Commit suggestion` button above.

2020-09-21 18:36 UTC, merged

2020-09-21 18:40 UTC, nisarhassan12 commented on packages/interface/cypress/integration/keyboard-shortcuts.spec.ts
> +      cy.get('.chakra-modal__header').contains('Create a Flashcard');
Thanks. @shicholas Looks like you have already committed the suggestion. Yeah. It makes a lot more sense to use `data-attributes` instead of any Chakra specific class names.